FROM eclipse-temurin:17
LABEL maintainer="dmanjunatha0706@gmail.com"
WORKDIR /app
COPY target/config-server-0.0.1-SNAPSHOT.jar /app/config-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","config-server-0.0.1-SNAPSHOT.jar"]